Repository crpg2/itembalancing, pull requests merged in 2025-01, with the labels that each got.

#535 Corerct mesh name
  items/body_armors.xml
Labels: Armour, Cosmetic

#561 Fixed collision and visual model to the correct one
  items/shields.xml
Labels: Shields

#562 Switches meshes to reworked ones from May.Ham
  items/arm_armors.xml
  items/leg_armors.xml
  items/shoulder_armors.xml
Labels: Armour
